/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.penjualan;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author deric
 */
public class GUIPenjualan extends javax.swing.JFrame {
public Statement st;
public ResultSet rs;
boolean edit; // berfungsi sebagai penanda apakah file ingin diedit atau tidak.
String sId; // berfungsi untuk menampung data id nantinya.
public DefaultTableModel tabModel;
Connection cn = Koneksi.Koneksi();

public GUIPenjualan() {
        initComponents();
        setVisible(true);
        judul();
        tampilData("");
        refresh();
    }

    public void judul() {
    Object[] judul = {"Kode Barang", "Nama Barang", "Harga", "Jumlah", "Sub-Total","Diskon","Pajak","Total Harga"};
    tabModel = new DefaultTableModel(null, judul);
    tblPenjualan.setModel(tabModel);
    }
    
    public void tampilData(String where) { 
    try {
    st = cn.createStatement();
    tabModel.getDataVector().removeAllElements();
    tabModel.fireTableDataChanged();
    rs = st.executeQuery("SELECT * FROM penjualan " + where);
    while (rs.next()) {
    Object[] data = {
    rs.getString("kodebarang"),
    rs.getString("namabarang"),
    rs.getString("harga"),
    rs.getString("jumlah"),
    rs.getString("subtotal"),
    rs.getString("diskon"),
    rs.getString("pajak"),
    rs.getString("total")
    };
    tabModel.addRow(data);
    }
    }catch(Exception e) {
    e.printStackTrace();
        }
    }
    
    public void refresh(){
    txtKode.setText("");
    txtNama.setText("");
    txtHarga.setText("");
    txtJumlah.setText("");
    txtSub.setText("");
    txtDiskon.setText("");
    txtPajak.setText("");
    txtTotal.setText("");
    txtKode.setEnabled(false);
    txtNama.setEnabled(false);
    txtHarga.setEnabled(false);
    txtJumlah.setEnabled(false);
    txtSub.setEnabled(false);
    txtDiskon.setEnabled(false);
    txtPajak.setEnabled(false);
    txtTotal.setEnabled(false);
    btnTambah.setEnabled(true);
    btnHitung.setEnabled(false);
    btnSimpan.setEnabled(false);
    btnEdit.setEnabled(false);
    btnHapus.setEnabled(false);
    btnBatal.setEnabled(false);
    btnSimpan.setText("Simpan");
    edit=false;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtSub = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penjualan");

        jLabel2.setText("Kode Barang");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Harga Barang");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Diskon");

        jLabel7.setText("Pajak");

        jLabel8.setText("Total Harga");

        jLabel9.setText("Sub-Total");

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenjualan);

        txtNama.setText("jTextField2");

        txtHarga.setText("jTextField3");

        txtJumlah.setText("jTextField4");

        txtSub.setText("jTextField5");
        txtSub.setEnabled(false);

        txtDiskon.setText("jTextField6");
        txtDiskon.setEnabled(false);

        txtPajak.setText("jTextField7");
        txtPajak.setEnabled(false);

        txtTotal.setText("jTextField8");
        txtTotal.setEnabled(false);

        txtKode.setText("jTextField1");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.setToolTipText("");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga)
                            .addComponent(txtNama)
                            .addComponent(txtSub)
                            .addComponent(txtDiskon)
                            .addComponent(txtPajak)
                            .addComponent(txtTotal)
                            .addComponent(txtKode)
                            .addComponent(txtJumlah))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnHitung)
                            .addComponent(btnSimpan)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit)
                            .addComponent(btnBatal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    txtKode.setEnabled(true);
    txtNama.setEnabled(true);
    txtHarga.setEnabled(true);
    txtJumlah.setEnabled(true);
    btnTambah.setEnabled(false);
    btnHitung.setEnabled(true);
    btnSimpan.setEnabled(false);
    btnEdit.setEnabled(false);
    btnHapus.setEnabled(false);
    btnBatal.setEnabled(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    Hitung H = new Hitung();
    if ((txtKode.getText().equals(""))||(txtNama.getText().equals(""))||(txtHarga.getText().equals(""))||(txtJumlah.getText().equals(""))){
        JOptionPane.showMessageDialog(null, "Data Masih Kosong!","Pesan Error", JOptionPane.ERROR_MESSAGE);
    }else {
        H.setKode(txtKode.getText());
        H.setNama(txtNama.getText());
        H.setHarga(Double.parseDouble(txtHarga.getText()));
        H.setJumlah(Double.parseDouble(txtJumlah.getText()));
        txtSub.setText(String.valueOf(H.getSubTotal()));
        txtDiskon.setText(String.valueOf(H.Diskon()));
        txtPajak.setText(String.valueOf(H.getPajak()));
        txtTotal.setText(String.valueOf(H.Total()));
        btnHitung.setEnabled(true);
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
    refresh();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
    st = cn.createStatement();
    if (edit) {
    st.executeUpdate("UPDATE penjualan set " +"kodebarang='"+ txtKode.getText() + "', "
    + "namabarang='" + txtNama.getText() + "'," + "harga='" + txtHarga.getText()+ "', "
    + "jumlah='" + txtJumlah.getText()+ "', "+ "subtotal='" + txtSub.getText() + "',"
    + "diskon='" + txtDiskon.getText() + "'," + "pajak='" + txtPajak.getText() + "',"
    + "total='" + txtTotal.getText() + "' WHERE kodebarang ='" + sId + "' ");
    }else {
    st.executeUpdate("INSERT INTO penjualan VALUES ('"+txtKode.getText()+"','"+txtNama.getText()+"','"+txtHarga.getText()+"','"+txtJumlah.getText()+"','"+txtSub.getText()+"','"+txtDiskon.getText()+"','"+txtPajak.getText()+"','"+txtTotal.getText()+"')"); // perintah untuk menginput data ke dalam database.
    }
    tampilData("");
    if (edit){
        JOptionPane.showMessageDialog(null, "Update Berhasil");
    }else {
        JOptionPane.showMessageDialog(null, "Simpan Berhasil");
    }
    refresh();
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    edit = true;
    txtKode.setEnabled(true);
    txtNama.setEnabled(true);
    txtHarga.setEnabled(true);
    txtJumlah.setEnabled(true);
    txtSub.setText("");
    txtDiskon.setText("");
    txtPajak.setText("");
    txtTotal.setText("");
    btnSimpan.setText("Update");
    btnHitung.setEnabled(true);
    btnSimpan.setEnabled(false);
    btnEdit.setEnabled(false);
    btnHapus.setEnabled(false);
    btnBatal.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
    int jawab;
    if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) { // konfirmasi untuk menghapus data.
    st = cn.createStatement();
    st.executeUpdate("DELETE FROM penjualan WHERE kodebarang='"+ tabModel.getValueAt(tblPenjualan.getSelectedRow(), 0) + "'"); // perintah sql untuk menghapus data dimana id = baris yang di pilih.
    tampilData(""); // tampil data.
    refresh(); // memanggil metode refresh.
    }
    } catch (Exception e) {
    e.printStackTrace();
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenjualanMouseClicked
    sId=(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 0).toString());
    txtKode.setText(sId);
    txtNama.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 1).toString());
    txtHarga.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 2).toString());
    txtJumlah.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 3).toString());
    txtSub.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 4).toString());
    txtDiskon.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 5).toString());
    txtPajak.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 6).toString());
    txtTotal.setText(tblPenjualan.getValueAt(tblPenjualan.getSelectedRow(), 7).toString());
    txtKode.setEnabled(false);
    txtNama.setEnabled(false);
    txtHarga.setEnabled(false);
    txtJumlah.setEnabled(false);
    btnHitung.setEnabled(false);
    btnSimpan.setEnabled(false);
    btnTambah.setEnabled(false);
    btnEdit.setEnabled(true);
    btnHapus.setEnabled(true);
    btnBatal.setEnabled(true);
    }//GEN-LAST:event_tblPenjualanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
